---

AllCops:
  TargetRubyVersion: 3.1.3
  NewCops: enable
  SuggestExtensions:
    rubocop-rails: true
    rubocop-performance: true
    rubocop-rake: true

require:
  - rubocop-rails
  - rubocop-rake
  - rubocop-performance

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

# Style/StringLiterals:
#   Enabled: true
#   EnforcedStyle: double_quotes

# Style/StringLiteralsInInterpolation:
#   Enabled: true
#   EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false
