---

AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable
  SuggestExtensions:
    rubocop-rails: true
    rubocop-performance: true
    rubocop-rake: true
    rubocop-capybara: true

require:
  - rubocop-rails
  - rubocop-rake
  - rubocop-performance

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
